// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:todo_list_pomodoro/data/models/label.dart';
import 'package:todo_list_pomodoro/data/models/pomodoro.dart';
import 'package:todo_list_pomodoro/data/models/task.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LabelAdapter());
    registerAdapter(PomodoroAdapter());
    registerAdapter(TaskAdapter());
  }
}
